//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebBikerBox.Entity.Estructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Anuncio
    {
        public string nombre { get; set; }
        public string provincia { get; set; }
        public string localidad { get; set; }
        public int id { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> cilindrada { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> km { get; set; }
        public string color { get; set; }
        public byte[] imagen { get; set; }
        public string correo { get; set; }
        public Nullable<double> precio { get; set; }
    }
}
