//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiWebBikerBox.Entity.Estructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_MotoIdUsuario
    {
        public Nullable<int> idUsuario { get; set; }
        public string matricula { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string estilo { get; set; }
        public Nullable<int> cilindrada { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<int> km { get; set; }
        public string color { get; set; }
        public int id { get; set; }
    }
}
